<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup><IsPackable>false</IsPackable></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/DnaX.Hosting/DnaX.Hosting.csproj" />
    <ProjectReference Include="../../src/DnaX.Data/DnaX.Data.csproj" />
    <ProjectReference Include="../../src/DnaX.Data.Migrations/DnaX.Data.Migrations.csproj" />
    <ProjectReference Include="../../src/DnaX.Data.Migrations.Sqlite/DnaX.Data.Migrations.Sqlite.csproj" />
    <ProjectReference Include="../../src/DnaX.Caching/DnaX.Caching.csproj" />
    <ProjectReference Include="../../src/DnaX.Diagnostics/DnaX.Diagnostics.csproj" />
    <ProjectReference Include="../../src/DnaX.Compatibility/DnaX.Compatibility.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
  </ItemGroup>
</Project>
